# fly.toml app configuration file generated for dawidgawronskidev-mini-message-board on 2024-02-06T11:21:32Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dawidgawronskidev-mini-message-board'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
