# fly.toml app configuration file generated for mini-message-board-express-node-red-snow-3963 on 2024-02-06T11:15:07Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mini-message-board-express-node-red-snow-3963'
primary_region = 'lhr'

[build]
  image = 'flyio/hellofly:latest'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
